### PR TITLE
Create creaters.json

### PR DESCRIPTION
**Pull request by JosephE2**
hi yes zordlan nacrt didnt make it so i did but its probably the wrong repo (i looked through everything and there is no creaters.json i also probably spelled it wrong but who gives a shit

### CODE REVIEW

**Comment by JosephE2** [comment]
welp nvm

**Comment by koxx12-dev** [comment]
Just crate a empty bracket

**Comment by koxx12-dev** [comment]
add*

**Comment by JoeyE2** [comment]
ok new pr

**Comment by nacrt** [comment]
close it yourself next time

**Pull request closed without merging**
