### PR TITLE
worlds and beyonds smallname is always wab

### PR DESCRIPTION
**Pull request by JosephE2**

### CODE REVIEW

**Comment by JosephE2** [comment]
i have committed mass murder

**Comment by koxx12-dev** [comment]
that id is also used in other places

**Review by koxx12-dev — CHANGES_REQUESTED** [review]
change them in other places and i will merge it

**Comment by Feel65** [comment]
got that Wet Ass 🅱️ussy

**Comment by Feel65** [comment]
got that wet ass bussy

**Comment by Zetvue** [comment]
the fuck

**Pull request closed without merging**
