### PR TITLE
a little (scamlink) trolling

### PR DESCRIPTION
**Pull request by JosephE2**

### CODE REVIEW

**Comment by IlluminatiFish** [comment]
example of where you found this scam being used?

**Comment by JosephE2** [comment]
dms

**Comment by JosephE2** [comment]
not sure if its up or what ip it's on

**Comment by JosephE2** [comment]
sah a couple of minutes ago

**Comment by IlluminatiFish** [comment]
> dms

bet IlluminatiFish#0753 add me

**Pull request merged**
